// TODO: replace with autogenerated OpenAPI client bindings.
export type ApiClientConfig = {
  baseUrl: string
  accessToken?: string
}

export const createApiClient = (config: ApiClientConfig) => {
  return {
    config,
  }
}
